### ISSUE TITLE
Template uses outdated META6.json format

### ISSUE THREAD

**Issue by niner** [JJ/raku-dist-template#3]
https://design.raku.org/S22.html#META6.json specifies e.g. the `meta-version` field as required.
`build-depends` and `test-depends` are legacy fields that should not be used anymore.
`"perl": "6.*"` doesn't mean anything. It's better to give a sensible default like `v6.d`, otherwise it will dissuade people from thinking about what minimum version they actually want to support.

**Comment by JJ** [comment]
Thanks, @niner . Will fix.
